title: GD Soluções e Consultoria
name: Your Name
email: your-email@example.com
description: A GD Soluções e Consultoria visa sempre a melhor solução possível para os nossos clientes, buscando tanto a excelência operacional quanto a melhor custo-benefício. Nossas principais áreas de experiência são Aplicativos Web, Aplicativos Mobile, Banco de Dados e o gerenciamento de processos de negócio. 

baseurl: "/blog"
url: ""

parallax_image_one: assets/images/startup3.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/startup3.jpg

project_one: Aplicativos Web
project_one_description: Elaboramos e produzimos sites, baseados nas melhores práticas de desenvolvimento, como a melhor experiência para o usuário e facilidade para a sua manutenção.
project_one_url: https://github.com/jameshamann/jekyll-material-theme
project_one_icon: location_on

project_two: Aplicativos Mobile
project_two_description: Desenvolvemos aplicativos para smartphones, que agregam um valor excepcional ao seu negócio nos dias de hoje, apresentando as mais diversas funcionalidades pretendidas pelo cliente.
project_two_url: https://github.com/jameshamann/jekyll-material-theme
project_two_icon: photo_camera


project_three: Banco de Dados
project_three_description: Realizamos desde a modelagem do banco de dados do seu negócio, passando pela engenharia reversa, até consultas avançadas em SQL.
project_three_url: https://github.com/jameshamann/jekyll-material-theme
project_three_icon: hotel


project_four: Gerenciamento de Processos
project_four_description: Com o conhecimento dos mais diversos processos de gerenciamento organizacionais, elaboramos a modelagem atual do seu negócio, utilizando as mais avançadas técnicas como a dinâmica de sistemas e o BPMN.
project_four_url: https://github.com/jameshamann/jekyll-material-theme
project_four_icon: restaurant

portfolio_heading: Nossas Soluções
portfolio_type: cards

syntax_highlighting: true
# Skill icons from https://konpa.github.io/devicon/

skills:
  - name: amazonwebservices
  - name: android
  - name: angularjs
  - name: apple
  - name: atom
  - name: bootstrap
  - name: c
  - name: chrome
  - name: coffescript
  - name: css3
  - name: cucumber
  - name: debian
  - name: devicon
  - name: django
  - name: docker
  - name: facebook
  - name: firefox
  - name: git
  - name: github
  - name: gitlab
  - name: google
  - name: gulp
  - name: heroku
  - name: html5
  - name: illustrator
  - name: itellij
  - name: java
  - name: javascript
  - name: linux
  - name: mongodb
  - name: mysql
  - name: nodejs
  - name: nodewebkit
  - name: oracle
  - name: photoshop
  - name: postgresql
  - name: python
  - name: rails
  - name: react
  - name: redhat
  - name: ruby
  - name: rubymine
  - name: safari
  - name: sass
  - name: slack
  - name: sourcetree
  - name: ssh
  - name: swift
  - name: tomcat
  - name: travis
  - name: trello
  - name: twitter
  - name: typescript
  - name: ubuntu
  - name: vim
  - name: visualstudio
  - name: vuejs
  - name: webpack
  - name: wordpress

icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons

project_button: Github

github: https://github.com/jameshamann/jekyll-material-theme
medium: https://medium.com

baseurl: # if your site is located at /blog or /home, enter it here, otherwise leave it empty
url: http://localhost:4000/ #the url of your site

# Google tracking, if both are filled, tag manager will prevail. Set up GA through GTM in that case
tag_manager_id: # This looks something like GTM-XXXXXXX
google_analytics_tracking_id: # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

cookies_banner: show # The value "show" will show the cookies banner, the value "none" will hide the banner.

cookie_accept_message: Thanks!

syntax_highlighting: true # include the css for syntax highlighting

# Build settings
markdown: kramdown
# theme: minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
